# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-11-13 19:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('pubdate', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(default='')),
                ('abstract', models.TextField(default='')),
                ('postType', models.CharField(db_index=True, max_length=50)),
                ('column_id', models.IntegerField(default=0)),
                ('image', models.CharField(default='', max_length=150)),
                ('order', models.IntegerField(default=0)),
                ('showInIndex', models.BooleanField(default=False)),
                ('views', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('favs', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PostMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=150)),
                ('value', models.CharField(blank=True, max_length=150)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Post')),
            ],
        ),
        migrations.CreateModel(
            name='PostTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=150)),
                ('tagType', models.CharField(max_length=150)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Post')),
            ],
        ),
        migrations.CreateModel(
            name='SiteBasic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settingName', models.CharField(max_length=150, unique=True)),
                ('settingValue', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SiteUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=150)),
                ('verified', models.BooleanField(default=False)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('verifyCode', models.CharField(max_length=10)),
                ('trueName', models.CharField(max_length=20)),
                ('gender', models.IntegerField(default=0)),
                ('birthday', models.DateField(null=True)),
                ('contact', models.CharField(max_length=200)),
                ('jobCompany', models.CharField(max_length=200)),
                ('jobPosition', models.CharField(max_length=20)),
                ('educationBackground', models.CharField(max_length=5)),
                ('educationSchool', models.CharField(max_length=200)),
                ('educationSpecialist', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SiteUserFav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likeOrFav', models.IntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.SiteUser')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='postmeta',
            unique_together=set([('post', 'field', 'value')]),
        ),
    ]
