# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-11-14 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='accessToken',
            field=models.CharField(db_index=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='contact',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='educationBackground',
            field=models.CharField(default='\u672c\u79d1', max_length=5),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='educationSchool',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='educationSpecialist',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='jobCompany',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='jobPosition',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='phoneNumber',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='trueName',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='verifyCode',
            field=models.CharField(default='', max_length=10),
        ),
    ]
