# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-11-14 11:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20171114_0854'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchKeyword', models.CharField(default='', max_length=50)),
                ('probabilityWeight', models.IntegerField(default=1)),
                ('banner', models.CharField(default='/static/images/banner.jpg', max_length=150)),
                ('url', models.CharField(default='/', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SiteUserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userGroup', models.CharField(default='', max_length=10)),
                ('userGroupTill', models.DateField(null=True)),
                ('remaining', models.IntegerField(default=0)),
                ('siteUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.SiteUser', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteUserAccountLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubdate', models.DateTimeField(auto_created=True)),
                ('change', models.IntegerField(default=0)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Post')),
                ('siteUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.SiteUser')),
            ],
        ),
        migrations.RenameField(
            model_name='siteuserfav',
            old_name='user',
            new_name='siteUser',
        ),
    ]
