# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-11-14 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20171114_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='securityAnswer',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='siteuser',
            name='securityQuestion',
            field=models.CharField(default='', max_length=150),
        ),
    ]
