# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-11-14 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20171114_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='showDetails',
            field=models.BooleanField(default=True),
        ),
    ]
