# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-11-16 17:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitebasic',
            name='settingDescription',
            field=models.TextField(default='', verbose_name='\u8bf4\u660e'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitebasic',
            name='settingValueType',
            field=models.TextField(default='', verbose_name='\u6570\u636e\u7c7b\u578b'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='banner',
            field=models.CharField(default='/static/images/banner.jpg', max_length=150, verbose_name='\u56fe\u7247'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='matchKeyword',
            field=models.CharField(default='', max_length=50, verbose_name='\u5173\u952e\u8bcd\u5339\u914d'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='probabilityWeight',
            field=models.IntegerField(default=1, verbose_name='\u6982\u7387\u6743\u91cd'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='url',
            field=models.CharField(default='/', max_length=200, verbose_name='\u94fe\u63a5\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='content',
            field=models.CharField(max_length=500, verbose_name='\u5185\u5bb9'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='pubdate',
            field=models.DateTimeField(auto_now=True, verbose_name='\u53d1\u9001\u65e5\u671f'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='read',
            field=models.BooleanField(default=False, verbose_name='\u5df2\u5f52\u6863'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='shop.SiteUser', verbose_name='\u53d1\u9001\u8005'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='siteUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='shop.SiteUser', verbose_name='\u6536\u4fe1\u4eba'),
        ),
        migrations.AlterField(
            model_name='post',
            name='abstract',
            field=models.TextField(default='', verbose_name='\u6458\u8981/\u95ee\u9898'),
        ),
        migrations.AlterField(
            model_name='post',
            name='allowComments',
            field=models.BooleanField(default=True, verbose_name='\u5141\u8bb8\u8bc4\u8bba'),
        ),
        migrations.AlterField(
            model_name='post',
            name='column_id',
            field=models.IntegerField(default=0, verbose_name='\u680f\u76eeID'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(default='', verbose_name='\u5185\u5bb9'),
        ),
        migrations.AlterField(
            model_name='post',
            name='favs',
            field=models.IntegerField(default=0, verbose_name='\u6536\u85cf\u6570'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.CharField(default='', max_length=150, verbose_name='\u9898\u56fe'),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='\u70b9\u8d5e\u6570'),
        ),
        migrations.AlterField(
            model_name='post',
            name='order',
            field=models.IntegerField(default=0, verbose_name='\u6392\u5e8f\u6743\u91cd'),
        ),
        migrations.AlterField(
            model_name='post',
            name='postType',
            field=models.CharField(db_index=True, max_length=50, verbose_name='\u9875\u9762\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pubdate',
            field=models.DateTimeField(auto_now=True, verbose_name='\u53d1\u5e03\u65e5\u671f'),
        ),
        migrations.AlterField(
            model_name='post',
            name='showInIndex',
            field=models.BooleanField(default=False, verbose_name='\u9996\u9875\u6eda\u52a8'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=150, verbose_name='\u6807\u9898'),
        ),
        migrations.AlterField(
            model_name='post',
            name='views',
            field=models.IntegerField(default=0, verbose_name='\u6d4f\u89c8\u6570'),
        ),
        migrations.AlterField(
            model_name='postmeta',
            name='field',
            field=models.CharField(max_length=150, verbose_name='\u5b57\u6bb5'),
        ),
        migrations.AlterField(
            model_name='postmeta',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Post', verbose_name='\u6240\u5c5e\u9875\u9762'),
        ),
        migrations.AlterField(
            model_name='postmeta',
            name='value',
            field=models.CharField(blank=True, max_length=150, verbose_name='\u503c'),
        ),
        migrations.AlterField(
            model_name='posttag',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Post', verbose_name='\u6240\u5c5e\u9875\u9762'),
        ),
        migrations.AlterField(
            model_name='posttag',
            name='tag',
            field=models.CharField(max_length=150, verbose_name='\u6807\u7b7e'),
        ),
        migrations.AlterField(
            model_name='posttag',
            name='tagType',
            field=models.CharField(max_length=150, verbose_name='\u6807\u7b7e\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='sitebasic',
            name='settingName',
            field=models.CharField(max_length=150, unique=True, verbose_name='\u8bbe\u7f6e\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='sitebasic',
            name='settingValue',
            field=models.TextField(verbose_name='\u8bbe\u5b9a\u503c'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='accessToken',
            field=models.CharField(db_index=True, max_length=150, null=True, verbose_name='Access Token'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='birthday',
            field=models.DateField(null=True, verbose_name='\u751f\u65e5'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='contact',
            field=models.CharField(default='', max_length=200, verbose_name='\u8054\u7cfb\u65b9\u5f0f'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='educationBackground',
            field=models.CharField(default='\u672c\u79d1', max_length=5, verbose_name='\u5b66\u5386'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='educationSchool',
            field=models.CharField(default='', max_length=200, verbose_name='\u5b66\u6821'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='educationSpecialist',
            field=models.CharField(default='', max_length=200, verbose_name='\u4e13\u4e1a'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='gender',
            field=models.IntegerField(default=0, verbose_name='\u6027\u522b'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='jobCompany',
            field=models.CharField(default='', max_length=200, verbose_name='\u516c\u53f8'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='jobPosition',
            field=models.CharField(default='', max_length=20, verbose_name='\u804c\u52a1'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='password',
            field=models.CharField(max_length=150, verbose_name='\u5bc6\u7801'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='phoneNumber',
            field=models.CharField(max_length=20, unique=True, verbose_name='\u624b\u673a\u53f7'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='securityAnswer',
            field=models.CharField(default='', max_length=150, verbose_name='\u5b89\u5168\u95ee\u9898\u7b54\u6848'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='securityQuestion',
            field=models.CharField(default='', max_length=150, verbose_name='\u5b89\u5168\u95ee\u9898'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='showDetails',
            field=models.BooleanField(default=True, verbose_name='\u516c\u5f00\u4e2a\u4eba\u4fe1\u606f'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='trueName',
            field=models.CharField(default='', max_length=20, verbose_name='\u771f\u5b9e\u59d3\u540d'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='username',
            field=models.CharField(max_length=50, unique=True, verbose_name='\u7528\u6237\u540d'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='\u542f\u7528'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='verifyCode',
            field=models.CharField(default='', max_length=10, verbose_name='\u9a8c\u8bc1\u7801'),
        ),
        migrations.AlterField(
            model_name='siteuseraccount',
            name='remaining',
            field=models.IntegerField(default=0, verbose_name='\u4f59\u989d'),
        ),
        migrations.AlterField(
            model_name='siteuseraccount',
            name='siteUser',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='shop.SiteUser', verbose_name='\u7528\u6237'),
        ),
        migrations.AlterField(
            model_name='siteuseraccount',
            name='userGroup',
            field=models.CharField(default='', max_length=10, verbose_name='\u4f1a\u5458\u7ec4\u522b'),
        ),
        migrations.AlterField(
            model_name='siteuseraccount',
            name='userGroupTill',
            field=models.DateField(null=True, verbose_name='\u6709\u6548\u671f\u81f3'),
        ),
        migrations.AlterField(
            model_name='siteuseraccountlog',
            name='change',
            field=models.IntegerField(default=0, verbose_name='\u91d1\u989d\u53d8\u52a8'),
        ),
        migrations.AlterField(
            model_name='siteuseraccountlog',
            name='ip',
            field=models.CharField(max_length=20, verbose_name='\u64cd\u4f5cIP\u5730\u5740/\u7cfb\u7edf\u8bbe\u5b9a\u539f\u56e0'),
        ),
        migrations.AlterField(
            model_name='siteuseraccountlog',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Post', verbose_name='\u6240\u8d2d\u7d20\u6750\u3001\u6559\u7a0b'),
        ),
        migrations.AlterField(
            model_name='siteuseraccountlog',
            name='pubdate',
            field=models.DateTimeField(auto_now=True, verbose_name='\u53d1\u751f\u65e5\u671f'),
        ),
        migrations.AlterField(
            model_name='siteuseraccountlog',
            name='siteUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.SiteUser', verbose_name='\u7528\u6237'),
        ),
        migrations.AlterField(
            model_name='siteuserfav',
            name='likeOrFav',
            field=models.IntegerField(default=0, verbose_name='\u70b9\u8d5e\uff080\uff09\u6216\u6536\u85cf\uff081\uff09'),
        ),
        migrations.AlterField(
            model_name='siteuserfav',
            name='siteUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.SiteUser', verbose_name='\u7528\u6237'),
        ),
    ]
