# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-11-17 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20171116_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='layout',
            field=models.IntegerField(default=0, verbose_name='\u5e03\u5c40'),
        ),
    ]
