# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-25 05:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_advertisement_layout'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteUserOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubdate', models.DateTimeField(auto_now=True, verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='SiteUserOrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1, verbose_name='Count')),
                ('subtotal', models.FloatField(default=0, verbose_name='Subtotal')),
            ],
        ),
        migrations.DeleteModel(
            name='Advertisement',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='siteUser',
        ),
        migrations.AlterUniqueTogether(
            name='postmeta',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='postmeta',
            name='post',
        ),
        migrations.RemoveField(
            model_name='posttag',
            name='post',
        ),
        migrations.RemoveField(
            model_name='siteuseraccount',
            name='siteUser',
        ),
        migrations.RemoveField(
            model_name='siteuseraccountlog',
            name='product',
        ),
        migrations.RemoveField(
            model_name='siteuseraccountlog',
            name='siteUser',
        ),
        migrations.RemoveField(
            model_name='siteuserfav',
            name='post',
        ),
        migrations.RemoveField(
            model_name='siteuserfav',
            name='siteUser',
        ),
        migrations.RemoveField(
            model_name='post',
            name='allowComments',
        ),
        migrations.RemoveField(
            model_name='post',
            name='favs',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='siteuser',
            name='accessToken',
        ),
        migrations.RemoveField(
            model_name='siteuser',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='siteuser',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='siteuser',
            name='educationBackground',
        ),
        migrations.RemoveField(
            model_name='siteuser',
            name='educationSchool',
        ),
        migrations.RemoveField(
            model_name='siteuser',
            name='educationSpecialist',
        ),
        migrations.RemoveField(
            model_name='siteuser',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='siteuser',
            name='jobCompany',
        ),
        migrations.RemoveField(
            model_name='siteuser',
            name='jobPosition',
        ),
        migrations.RemoveField(
            model_name='siteuser',
            name='phoneNumber',
        ),
        migrations.RemoveField(
            model_name='siteuser',
            name='securityAnswer',
        ),
        migrations.RemoveField(
            model_name='siteuser',
            name='securityQuestion',
        ),
        migrations.RemoveField(
            model_name='siteuser',
            name='showDetails',
        ),
        migrations.RemoveField(
            model_name='siteuser',
            name='trueName',
        ),
        migrations.RemoveField(
            model_name='siteuser',
            name='verified',
        ),
        migrations.RemoveField(
            model_name='siteuser',
            name='verifyCode',
        ),
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.FloatField(default=0, verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='siteuser',
            name='authority',
            field=models.IntegerField(default=False, verbose_name='Authority'),
        ),
        migrations.AlterField(
            model_name='post',
            name='abstract',
            field=models.TextField(default='', verbose_name='Abstract'),
        ),
        migrations.AlterField(
            model_name='post',
            name='column_id',
            field=models.IntegerField(default=0, verbose_name='Shop ID'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(default='', verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.CharField(default='', max_length=150, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='post',
            name='postType',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Page Type'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pubdate',
            field=models.DateTimeField(auto_now=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='post',
            name='showInIndex',
            field=models.BooleanField(default=False, verbose_name='Featured'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='post',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Views'),
        ),
        migrations.AlterField(
            model_name='sitebasic',
            name='settingDescription',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='sitebasic',
            name='settingName',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='sitebasic',
            name='settingValue',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sitebasic',
            name='settingValueType',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='password',
            field=models.CharField(max_length=150, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='username',
            field=models.CharField(max_length=50, unique=True, verbose_name='Username'),
        ),
        migrations.DeleteModel(
            name='Notifications',
        ),
        migrations.DeleteModel(
            name='PostMeta',
        ),
        migrations.DeleteModel(
            name='PostTag',
        ),
        migrations.DeleteModel(
            name='SiteUserAccount',
        ),
        migrations.DeleteModel(
            name='SiteUserAccountLog',
        ),
        migrations.DeleteModel(
            name='SiteUserFav',
        ),
        migrations.AddField(
            model_name='siteuserorderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Post', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='siteuserorder',
            name='orderItem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.SiteUserOrderItem', verbose_name='Ordering Item'),
        ),
        migrations.AddField(
            model_name='siteuserorder',
            name='siteUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.SiteUser', verbose_name='User'),
        ),
    ]
