# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-25 06:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20180125_0515'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.SiteUser', verbose_name='Owner'),
            preserve_default=False,
        ),
    ]
