# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-25 07:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_post_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteuserorder',
            name='orderItem',
        ),
        migrations.AddField(
            model_name='siteuserorderitem',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.SiteUserOrder', verbose_name='Order'),
            preserve_default=False,
        ),
    ]
