# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-25 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20180125_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuserorder',
            name='dealt',
            field=models.BooleanField(default=False),
        ),
    ]
