# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-25 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_siteuserorder_dealt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuserorder',
            name='dealt',
            field=models.BooleanField(default=False, verbose_name='Dealt'),
        ),
    ]
